steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for d in */; do
      config="${d}cloudbuild.yaml"
      if [[ ! -f "${config}" ]]; then
        continue
      fi

      echo "Building $d ... "
      (
        gcloud builds submit $d --config=${config}
      ) &
    done
    wait

images:
    - "gcr.io/$PROJECT_ID/fc-sum-golang:latest"
    - "gcr.io/$PROJECT_ID/fc-sum-golang:1.0"
